name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  mobile_scanner: ^5.1.1
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  video_player: ^2.8.6
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true